allow_licenses:
  - Apache-1.1
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - BSL-1.0
  - ISC
  - MIT
  - NCSA
  - OpenSSL
  - Python-2.0
  - X11
allow-dependencies-licenses:
  - 'pkg:githubactions/fossas/fossa-action'
  - 'pkg:golang/github.com/shoenig/go-m1cpu'
  - 'pkg:pypi/pytest-metadata'
comment-summary-in-pr: on-failure
