name: Sync labels

on:
  push:
    paths:
      - labels.yml
  schedule:
    - cron: "8 0 * * 1" # run every Monday at 00:08 UTC
  workflow_dispatch: # yamllint disable-line rule:empty-values

concurrency:
  group: ${{ github.ref_name }}-sync
  cancel-in-progress: true

jobs:
  # This job sync the labels across the various repos
  labels-sync:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.fork == false }}
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Sync Labels
        uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c # v1.3.0
        with:
          manifest: labels.yml
          repository: |
            nginxinc/kubernetes-ingress
            nginxinc/kic-test-containers
            nginxinc/nginx-ingress-helm-operator
            nginxinc/nginx-prometheus-exporter
            nginxinc/nginx-plus-go-client
            nginxinc/nginx-asg-sync
            nginxinc/telemetry-exporter
          token: ${{ secrets.NGINX_PAT }}
          prune: true

  sync-repos:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - run: |
          gh repo sync nginx-bot/certified-operators
          gh repo sync nginxinc/winget-pkgs
          gh repo sync nginxinc/kubernetes-json-schema
        env:
          GITHUB_TOKEN: ${{ secrets.NGINX_PAT }}
